import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Logo from "./assets/quiz_logo-removebg-preview.png"
import Image from "next/image";
const inter = Quicksand({ 
  subsets: ["latin"],
  variable:"--font-quicksand"


});

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body className=' bg-white p-2'>
        <main className={`${inter.variable}font-quicksand max-w-[900px] w-full flex mx-auto flex-col items-center`}>
        <Image src={Logo} className=" w-[250px] -mt-[37px] -mb-[20px] h-[250px] "  alt={"logo"}/>
        {children}
        </main>
        
        </body>
    </html>
  );
}
